language: node_js
node_js: 8
env: 
  - $NODE_VERSION="8.7"
matrix:
  include:
    # Unit Tests
    - install:
      - yarn install
      script:
      - yarn test
      after_script:
      - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls'

    # E2E Web
    - install:
      - cd example/react-example
      - yarn install
      before_script:
      - yarn run build
      script:
      - yarn test

    # E2E XCode 9
    - language: objective-c
      os: osx
      osx_image: xcode9
      cache: yarn
      before_install:
      - brew tap wix/brew
      - brew install applesimutils --HEAD
      - nvm install $NODE_VERSION;
      - nvm use --delete-prefix $NODE_VERSION;
      - curl -o- -L https://yarnpkg.com/install.sh | bash -s
      - export PATH="$HOME/.yarn/bin:$PATH"
      - yarn global add react-native-cli detox-cli >/dev/null 2>&1
      install:
      - cd example/react-native-example
      - yarn
      script:
      - yarn run test:ios

    # E2E Tests android
    - language: android
      os: linux
      jdk: oraclejdk8
      env:
        - ANDROID_TARGET=android-25
        - ANDROID_ABI=x86
        - NODE_VERSION="8.7"
      android:
        components:
          - build-tools-25.0.3
          - android-25
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - sys-img-armeabi-v7a-android-26
      before_install:
      - nvm install $NODE_VERSION;
      - nvm use --delete-prefix $NODE_VERSION;
      - curl -o- -L https://yarnpkg.com/install.sh | bash -s
      - export PATH="$HOME/.yarn/bin:$PATH"
      - android list targets
      - echo no | android create avd --force -n Nexus_5X_API_25 -t android-25
      - emulator -avd Nexus_5X_API_25 -no-skin -no-audio -no-window &
      install:
      - cd example/react-native-example
      - yarn
      script:
      - android-wait-for-emulator
      - adb shell input keyevent 82 &
      - yarn run test:android
