language: node_js
node_js: 8
env: 
  - NODE_VERSION="8.7"
matrix:
  include:
    # Unit Tests
    - install:
      - yarn install
      script:
      - yarn test
      after_script:
      - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls'